<?php
declare(strict_types=1);

require_once __DIR__ . '/db.php';

// GRACE MODE: while false, requests without a valid token are still accepted
// (only logged) so existing callers (CcswAgent, CcswPopup, the browser
// extension) keep working while the token gets distributed to them. Flip to
// true once auth.log shows no more tokenless traffic, and tokenless/bad
// requests start getting a 401 instead.
const AUTH_ENFORCE = true;

const AUTH_HEADER = 'X-CCSW-Token';

// The PRIMARY shared secret -- the one handed out to browsers (index.php's
// ?token= login sets it as the ccsw_token cookie, feed.php embeds it for its
// own fetches). Always auth.config.php's 'token' key.
//
// This is NOT the full set of secrets the relay ACCEPTS -- see authTokens()
// below and requireAuth(). Anything issuing or embedding a credential wants
// this one; anything VALIDATING one wants the set.
//
// Reads from the private dir's auth.config.php, generating one on first use
// (mirrors how getDb() lazily creates jobs.sqlite there). Lives outside the web
// root / dist mirror so redeploys never regenerate or clobber it.
function authToken(): string
{
    static $token = null;
    if ($token !== null) {
        return $token;
    }

    $configFile = privateDir() . '/auth.config.php';
    if (is_file($configFile)) {
        $config = require $configFile;
        if (is_array($config) && !empty($config['token'])) {
            $token = (string) $config['token'];
            return $token;
        }
    }

    $token = bin2hex(random_bytes(32));
    $php = "<?php\n"
        . "declare(strict_types=1);\n"
        . "// Auto-generated by auth.php on first request. Do not commit.\n"
        . "return ['token' => " . var_export($token, true) . "];\n";
    file_put_contents($configFile, $php, LOCK_EX);
    @chmod($configFile, 0600);
    return $token;
}

// Every secret the relay ACCEPTS: the primary 'token' plus any additional ones
// in auth.config.php's optional 'tokens' => [...] list. Any token in the set is
// equally valid on every endpoint -- this is a flat set, not a hierarchy, and
// carries no per-token identity or scope.
//
// M1 multi-machine targeting is what motivates the list: a second machine's
// agent needs its own credential, so it can be revoked (or rotated) on its own
// without re-issuing the VM's token to every other caller. Purely additive --
// a config with only 'token' produces a one-element set and behaves exactly as
// it did before this existed.
//
// Never log or echo these. requireAuth() below logs only the OUTCOME of a check
// (missing/invalid) and never the value that was offered.
function authTokens(): array
{
    static $tokens = null;
    if ($tokens !== null) {
        return $tokens;
    }

    // authToken() first: it also owns first-use generation of the config file,
    // so calling it here means the extras below are read from a file that is
    // guaranteed to exist.
    $tokens = [authToken()];

    $configFile = privateDir() . '/auth.config.php';
    if (is_file($configFile)) {
        $config = require $configFile;
        if (is_array($config) && isset($config['tokens']) && is_array($config['tokens'])) {
            foreach ($config['tokens'] as $extra) {
                if (is_string($extra) && $extra !== '') {
                    $tokens[] = $extra;
                }
            }
        }
    }

    $tokens = array_values(array_unique($tokens));
    return $tokens;
}

function authConfigPath(): string
{
    return privateDir() . '/auth.config.php';
}

// Read auth.config.php fresh from disk, bypassing both the static caches above
// and opcache. The mint/revoke pair below is a read-modify-write of a file that
// authToken()/authTokens() memoise for the request, so re-using those here
// would happily write back a stale set and drop a token someone else just
// added. Everything that VALIDATES wants the cached authTokens(); only the
// writers want this.
function readAuthConfig(): array
{
    authToken(); // owns first-use generation -- guarantees the file exists.
    $file = authConfigPath();
    if (function_exists('opcache_invalidate')) {
        @opcache_invalidate($file, true);
    }
    $config = require $file;
    return is_array($config) ? $config : [];
}

// Rewrite auth.config.php whole, preserving every key it already had (only
// 'tokens' is ever touched by the callers below). var_export round-trips the
// values as PHP source, same shape authToken() writes on first use.
//
// Written to a temp file and renamed rather than truncated in place: this file
// is `require`d by every single request, and a partial write would take the
// WHOLE relay down (fatal parse error on a half-written file), locking out the
// very page you'd fix it from. rename() is atomic, so a concurrent request sees
// either the old file or the new one, never a fragment.
function writeAuthConfig(array $config): void
{
    $file = authConfigPath();
    $php = "<?php\n"
        . "declare(strict_types=1);\n"
        . "// Auto-generated by auth.php. Do not commit.\n"
        . "return " . var_export($config, true) . ";\n";

    $tmp = $file . '.tmp';
    if (file_put_contents($tmp, $php, LOCK_EX) === false) {
        throw new RuntimeException('could not write auth config');
    }
    @chmod($tmp, 0600);
    if (!rename($tmp, $file)) {
        @unlink($tmp);
        throw new RuntimeException('could not replace auth config');
    }
    @chmod($file, 0600);
    if (function_exists('opcache_invalidate')) {
        @opcache_invalidate($file, true);
    }
}

// Serialise the read-modify-write below across requests. Two mints landing at
// once would otherwise both read the same 'tokens' list and the second's write
// would silently erase the first's token -- a machine whose installer works
// until the moment the next one is provisioned. The lock is a separate file so
// taking it can never disturb the config itself.
function withAuthConfigLock(callable $fn)
{
    $handle = fopen(privateDir() . '/auth.config.lock', 'c');
    if ($handle === false) {
        throw new RuntimeException('could not open auth config lock');
    }
    try {
        flock($handle, LOCK_EX);
        return $fn();
    } finally {
        flock($handle, LOCK_UN);
        fclose($handle);
    }
}

// Grant a token: append it to auth.config.php's 'tokens' list. Additive and
// idempotent -- re-granting an already-present token is a no-op, not a
// duplicate. The token value is never logged; callers must not echo it either
// (machines.php only ever hands it to machine_installer.php).
function addAuthToken(string $token): void
{
    withAuthConfigLock(function () use ($token) {
        $config = readAuthConfig();
        $tokens = isset($config['tokens']) && is_array($config['tokens']) ? $config['tokens'] : [];
        $tokens = array_values(array_filter($tokens, fn($t) => is_string($t) && $t !== ''));
        if (!in_array($token, $tokens, true)) {
            $tokens[] = $token;
        }
        $config['tokens'] = array_values(array_unique($tokens));
        writeAuthConfig($config);
    });
}

// Revoke a token: drop it from the 'tokens' list.
//
// The primary 'token' is untouchable. It is the credential the browser holds
// (index.php's cookie), the VM agent runs on, and every deploy/verify tool
// reads -- revoking it would lock every caller out of the relay at once,
// including the page doing the revoking, with no way back in short of SSH. So
// this only ever edits the 'tokens' list and leaves 'token' alone; a request to
// revoke the primary value is refused outright rather than silently ignored.
function removeAuthToken(string $token): void
{
    if (hash_equals(authToken(), $token)) {
        throw new RuntimeException('refusing to revoke the primary token');
    }
    withAuthConfigLock(function () use ($token) {
        $config = readAuthConfig();
        $tokens = isset($config['tokens']) && is_array($config['tokens']) ? $config['tokens'] : [];
        $config['tokens'] = array_values(array_filter(
            $tokens,
            fn($t) => is_string($t) && $t !== '' && !hash_equals($token, $t)
        ));
        writeAuthConfig($config);
    });
}

// getallheaders() is Apache/LiteSpeed-only; the HTTP_ fallback covers the
// PHP built-in server used for local dev.
//
// One shared secret, two transports: programmatic clients (CcswAgent,
// CcswPopup, the browser extension) send it as the X-CCSW-Token header, but
// a browser navigating straight to a page can't attach a custom header to
// that navigation -- so it falls back to the ccsw_token cookie instead.
// Same token either way; every caller of requireAuth() picks up both
// transports for free.
function requestToken(): ?string
{
    if (function_exists('getallheaders')) {
        foreach (getallheaders() as $name => $value) {
            if (strcasecmp($name, AUTH_HEADER) === 0) {
                return $value;
            }
        }
    }
    $serverKey = 'HTTP_' . str_replace('-', '_', strtoupper(AUTH_HEADER));
    if (isset($_SERVER[$serverKey])) {
        return $_SERVER[$serverKey];
    }
    return $_COOKIE['ccsw_token'] ?? null;
}

function logAuthEvent(string $reason): void
{
    $line = sprintf(
        "[%s] endpoint=%s ip=%s reason=%s ua=%s\n",
        isoNow(),
        $_SERVER['SCRIPT_NAME'] ?? 'unknown',
        $_SERVER['REMOTE_ADDR'] ?? 'unknown',
        $reason,
        $_SERVER['HTTP_USER_AGENT'] ?? 'unknown'
    );
    @file_put_contents(privateDir() . '/auth.log', $line, FILE_APPEND | LOCK_EX);
}

// Shared auth gate -- every endpoint calls this right after requiring
// db.php. See AUTH_ENFORCE above for the grace-mode behaviour.
function requireAuth(): void
{
    $provided = requestToken();

    // hash_equals per candidate rather than in_array: the set is tiny (one
    // token per machine), and this keeps every comparison constant-time, same
    // as the single-token check it replaces.
    if ($provided !== null) {
        foreach (authTokens() as $expected) {
            if (hash_equals($expected, $provided)) {
                return;
            }
        }
    }

    logAuthEvent($provided === null ? 'missing' : 'invalid');

    if (AUTH_ENFORCE) {
        jsonResponse(['error' => 'unauthorized'], 401);
        exit;
    }
}

// Stricter gate for the ADMIN surface (machines.php, machine_installer.php):
// the primary token only, not the whole accepted set.
//
// requireAuth()'s set is deliberately flat -- every token is equally valid on
// every endpoint, carrying no identity or scope (see authTokens()). That is
// fine for the job endpoints, where a machine acting as another machine gains
// it nothing, but it does not hold for provisioning: gating minting on the flat
// set would let ANY provisioned machine's agent token mint further tokens or
// revoke its peers, so one compromised box would own the fleet. That is a
// privilege escalation, not a feature -- the machine tokens exist precisely so
// a box can be trusted with jobs WITHOUT being trusted with the relay.
//
// So these two pages want the credential the human has (index.php's ccsw_token
// cookie / the VM's own token), which is exactly authToken(). Both transports
// still work -- requestToken() is unchanged -- and requireAuth() still runs
// first, so the house rule holds and the 401 shape is identical either way.
// download.php deliberately does NOT use this: the installer fetches the agent
// zip with the machine's own token, which is the whole point of that token.
function requirePrimaryAuth(): void
{
    requireAuth();

    $provided = requestToken();
    if ($provided !== null && hash_equals(authToken(), $provided)) {
        return;
    }

    // Reached only by a caller holding a VALID non-primary token, so this is a
    // real escalation attempt (or a confused agent), not routine 401 noise.
    logAuthEvent('non-primary token on admin endpoint');
    jsonResponse(['error' => 'unauthorized'], 401);
    exit;
}
