/**
 * AUTO-GENERATED by tools/build-web.mjs -- DO NOT EDIT BY HAND.
 * Regenerate with: node tools/build-web.mjs
 *
 * Self-contained bundle: no import/require/fetch/DOM. Safe to load in a
 * browser extension service worker or content script. Attaches
 * globalThis.betterVoices = { normalize, splitWord, profiles, version }.
 */
(function () {
  'use strict';

  /**
   * Pure, dependency-free implementation of the better-voices pipeline.
   *
   * This is the SINGLE SOURCE OF TRUTH for the algorithm in JavaScript: it
   * takes already-loaded data (no fs/network access) and returns a
   * normalizer. lib/js/betterVoices.js wraps this for Node (loading JSON
   * from disk via fs), and tools/build-web.mjs embeds this file verbatim
   * into dist/better-voices.web.js for browser/service-worker use. Keep
   * lib/python/better_voices.py behaviorally in sync with this file.
   *
   * @param {{pronunciations: object, splitWords: object, acronyms: object, replacements: object, regexRules: object, profiles: object}} data
   * @returns {{normalize: function(string, string=): string, splitWord: function(string, string=): string}}
   */
  function createNormalizer(data) {
    const pronunciationMap = data.pronunciations.map;
    const splitMap = data.splitWords.map;
    const acronymMap = data.acronyms.map;
    const replacementRules = data.replacements.rules;
    const regexRuleList = data.regexRules.rules;
    const profiles = data.profiles;
  
    function escapeRegExp(literal) {
      return literal.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
    }
  
    function applyPronunciations(text) {
      for (const key of Object.keys(pronunciationMap)) {
        const regex = new RegExp('\\b' + escapeRegExp(key) + '\\b', 'gi');
        text = text.replace(regex, pronunciationMap[key]);
      }
      return text;
    }
  
    function getProfile(profileName) {
      const profileData = profiles[profileName];
      if (!profileData) {
        throw new Error('Unknown profile: ' + profileName);
      }
      return profileData;
    }
  
    function splitWord(word, profileName) {
      const profileData = getProfile(profileName || 'default');
      const caseInsensitive = (profileData.options || {}).caseInsensitiveSplitLookup || false;
  
      if (Object.prototype.hasOwnProperty.call(splitMap, word)) {
        return splitMap[word];
      }
  
      if (caseInsensitive) {
        const lowered = word.toLowerCase();
        for (const key of Object.keys(splitMap)) {
          if (key.toLowerCase() === lowered) {
            return splitMap[key];
          }
        }
      }
  
      return word;
    }
  
    function applySplitWords(text, profileData) {
      const caseInsensitive = (profileData.options || {}).caseInsensitiveSplitLookup || false;
  
      if (caseInsensitive) {
        const lookup = {};
        for (const key of Object.keys(splitMap)) {
          lookup[key.toLowerCase()] = splitMap[key];
        }
        return text.replace(/[A-Za-z0-9]+/g, (token) => {
          const lowered = token.toLowerCase();
          return Object.prototype.hasOwnProperty.call(lookup, lowered) ? lookup[lowered] : token;
        });
      }
  
      return text.replace(/[A-Za-z0-9]+/g, (token) => (
        Object.prototype.hasOwnProperty.call(splitMap, token) ? splitMap[token] : token
      ));
    }
  
    function applyRegex(text, step) {
      const use = step.use || 'all';
      const selectedIds = use === 'all' ? null : new Set(use);
  
      for (const rule of regexRuleList) {
        if (selectedIds !== null && !selectedIds.has(rule.id)) {
          continue;
        }
  
        if (rule.id === 'collapse-space') {
          text = text.replace(/\s+/g, ' ');
          continue;
        }
  
        if (!rule.pattern || rule.replace === undefined) {
          continue;
        }
  
        const flags = rule.flags || 'g';
        const regex = new RegExp(rule.pattern, flags);
        text = text.replace(regex, rule.replace);
      }
  
      return text;
    }
  
    function applyAcronyms(text) {
      return text.replace(/[A-Za-z0-9]+/g, (token) => (
        Object.prototype.hasOwnProperty.call(acronymMap, token) ? acronymMap[token] : token
      ));
    }
  
    function applyReplacements(text) {
      for (const rule of replacementRules) {
        const literal = rule.literal !== false;
        if (literal) {
          text = text.split(rule.find).join(rule.replace);
        } else {
          text = text.replace(new RegExp(rule.find, 'g'), rule.replace);
        }
      }
      return text;
    }
  
    function normalize(text, profileName) {
      const profileData = getProfile(profileName || 'default');
      const options = profileData.options || {};
  
      for (const step of profileData.pipeline) {
        switch (step.step) {
          case 'pronunciations':
            text = applyPronunciations(text);
            break;
          case 'split-words':
            text = applySplitWords(text, profileData);
            break;
          case 'regex':
            text = applyRegex(text, step);
            break;
          case 'acronyms':
            text = applyAcronyms(text);
            break;
          case 'replacements':
            text = applyReplacements(text);
            break;
          default:
            break;
        }
      }
  
      if (options.collapseWhitespace) {
        text = text.replace(/\s+/g, ' ');
      }
  
      if (options.trimResult) {
        text = text.replace(/\s+/g, ' ').trim();
      }
  
      return text;
    }
  
    return { normalize, splitWord };
  }
  
  if (typeof module !== 'undefined' && module.exports) {
    module.exports = { createNormalizer };
  }
  
  var data = {
    pronunciations: {
  "version": 1,
  "description": "Whole-word pronunciation respellings. Each key is matched as a whole word, case-insensitively, anywhere in the text, and replaced with the value, which is how it should sound when spoken.",
  "map": {
    "todos": "too doos",
    "todo": "too doo"
  }
},
    splitWords: {
  "version": 1,
  "description": "Starter set of run-together / acronym-smashed words mapped to their spaced-out spoken form. Keys are case-sensitive exact matches. Values here are PURE spacing/expansion only -- they must NOT bake in acronym letter-spelling (leave acronym tokens like JS, DB, QL, SQL, TTS, CCSW, VM intact and let data/acronyms.json decide how those are spoken). This is a small seed set -- expand freely as new mis-pronunciations are found. Entries under the 'ecosystem vocab' heading below are best-guess pronunciations for Jody's own projects/tools -- tweak as you hear them mis-spoken.",
  "map": {
    "AppData": "App Data",
    "PowerShell": "Power Shell",
    "PubSub": "Pub Sub",
    "WiFi": "Wi Fi",
    "GitHub": "Git Hub",
    "GitLab": "Git Lab",
    "DateTime": "Date Time",
    "JavaScript": "Java Script",
    "TypeScript": "Type Script",
    "NodeJS": "Node JS",
    "WebSocket": "Web Socket",
    "OAuth": "O Auth",
    "GraphQL": "Graph QL",
    "SQLite": "SQL Lite",
    "MySQL": "My SQL",
    "PostgreSQL": "Postgres SQL",
    "MongoDB": "Mongo DB",
    "DevOps": "Dev Ops",
    "BackEnd": "Back End",
    "FrontEnd": "Front End",
    "FileSystem": "File System",
    "CheckBox": "Check Box",
    "DropDown": "Drop Down",
    "TouchScreen": "Touch Screen",
    "HTMLParser": "HTML Parser",
    "VBoxSvr": "V Box Server",
    "BrainMop": "Brain Mop",
    "dabblelabs": "dabble labs",
    "DabbleLabs": "Dabble Labs",
    "redditwatch": "reddit watch",
    "RedditWatch": "Reddit Watch",
    "SleepTracker": "Sleep Tracker",
    "WeedModerator": "Weed Moderator",
    "hostcmd": "host command",
    "ccswitchboard": "C C Switchboard",
    "CCswitchboard": "C C Switchboard",
    "CCSwitchboard": "C C Switchboard",
    "EnvConf": "Env Config",
    "ADHDreminder": "A D H D reminder"
  }
},
    acronyms: {
  "version": 1,
  "description": "Acronym pronunciation lookup. Value is the spoken form: letters separated by spaces means spell it out, a plain word means say it as a word.",
  "map": {
    "SQL": "sequel",
    "URL": "U R L",
    "URI": "U R I",
    "GUI": "gooey",
    "API": "A P I",
    "JSON": "Jason",
    "CLI": "C L I",
    "SKU": "skew",
    "YAML": "yammel",
    "HTML": "H T M L",
    "CSS": "C S S",
    "HTTP": "H T T P",
    "HTTPS": "H T T P S",
    "XML": "X M L",
    "PDF": "P D F",
    "USB": "U S B",
    "RAM": "ram",
    "CPU": "C P U",
    "GPU": "G P U",
    "SSH": "S S H",
    "CCSW": "C C S W",
    "TTS": "T T S",
    "VM": "V M",
    "JS": "J S",
    "DB": "D B",
    "QL": "Q L",
    "ID": "I D",
    "APK": "A P K",
    "ADB": "A D B",
    "MV3": "M V 3"
  }
},
    replacements: {
  "version": 1,
  "description": "Ordered literal-string replacement rules, applied in list order. literal:true means a plain (non-regex) string replace. Multi-character rules are listed before single-character rules so overlapping symbols resolve correctly.",
  "rules": [
    {
      "find": "->",
      "replace": " to ",
      "literal": true
    },
    {
      "find": "<=",
      "replace": " less than or equal to ",
      "literal": true
    },
    {
      "find": ">=",
      "replace": " greater than or equal to ",
      "literal": true
    },
    {
      "find": "!=",
      "replace": " not equal to ",
      "literal": true
    },
    {
      "find": "+",
      "replace": " and ",
      "literal": true
    },
    {
      "find": "&",
      "replace": " and ",
      "literal": true
    },
    {
      "find": "@",
      "replace": " at ",
      "literal": true
    },
    {
      "find": "%",
      "replace": " percent ",
      "literal": true
    },
    {
      "find": "#",
      "replace": " number ",
      "literal": true
    },
    {
      "find": "_",
      "replace": " ",
      "literal": true
    },
    {
      "find": "=",
      "replace": " equals ",
      "literal": true
    },
    {
      "find": "$",
      "replace": " dollars ",
      "literal": true
    },
    {
      "find": "*",
      "replace": " star ",
      "literal": true
    },
    {
      "find": "/",
      "replace": " slash ",
      "literal": true
    },
    {
      "find": "\\",
      "replace": " backslash ",
      "literal": true
    },
    {
      "find": "~",
      "replace": " tilde ",
      "literal": true
    }
  ]
},
    regexRules: {
  "version": 1,
  "description": "Regex-based splitting rules. Patterns and replacements are stored in JavaScript regex style ($1, $2 backreferences). Consumers targeting other regex flavors (e.g. Python's re) must translate backreferences accordingly. Rules with no pattern/replace (e.g. collapse-space) are handled as built-in special cases by the reference libs.",
  "rules": [
    {
      "id": "camel-lower-upper",
      "pattern": "([a-z])([A-Z])",
      "replace": "$1 $2",
      "flags": "g",
      "note": "appData -> app Data"
    },
    {
      "id": "acronym-word",
      "pattern": "([A-Z]+)([A-Z][a-z])",
      "replace": "$1 $2",
      "flags": "g",
      "note": "HTMLParser -> HTML Parser"
    },
    {
      "id": "letter-digit",
      "pattern": "([A-Za-z])([0-9])",
      "replace": "$1 $2",
      "flags": "g",
      "note": "Base64 -> Base 64"
    },
    {
      "id": "digit-letter",
      "pattern": "([0-9])([A-Za-z])",
      "replace": "$1 $2",
      "flags": "g",
      "note": "64bit -> 64 bit"
    },
    {
      "id": "collapse-space",
      "note": "collapse runs of whitespace to a single space; built-in step, has no pattern/replace of its own"
    }
  ]
},
    profiles: {
  "default": {
    "version": 1,
    "name": "default",
    "description": "Baseline profile suitable for most TTS engines: split known joined words, apply all regex splitters, expand acronyms, then apply symbol/phrase replacements.",
    "pipeline": [
      {
        "step": "pronunciations"
      },
      {
        "step": "split-words"
      },
      {
        "step": "regex",
        "use": "all"
      },
      {
        "step": "acronyms"
      },
      {
        "step": "replacements"
      }
    ],
    "options": {
      "caseInsensitiveSplitLookup": true,
      "trimResult": true
    }
  },
  "example-sapi5": {
    "version": 1,
    "name": "sapi5",
    "description": "Example per-announcer override profile for a SAPI5-style engine. This engine already spells out acronyms on its own, so the acronyms step is OMITTED here to avoid double-processing. Case-insensitive split lookup is also turned off since this engine is picky about exact casing. Use this file as a template for adding your own announcer-specific profile.",
    "pipeline": [
      {
        "step": "split-words"
      },
      {
        "step": "regex",
        "use": "all"
      },
      {
        "step": "replacements"
      }
    ],
    "options": {
      "caseInsensitiveSplitLookup": false,
      "trimResult": true
    }
  },
  "webspeech": {
    "version": 1,
    "name": "webspeech",
    "description": "Targets the Chrome/Brave built-in Web Speech API default voice, as used by the CCswitchboard browser extension to announce thread/job/status phrases (e.g. 'Starting <thread> - <jobName>', 'completed (<thread>) Phase <n>', 'Refresh this tab').",
    "pipeline": [
      {
        "step": "pronunciations"
      },
      {
        "step": "split-words"
      },
      {
        "step": "regex",
        "use": "all"
      },
      {
        "step": "acronyms"
      },
      {
        "step": "replacements"
      }
    ],
    "options": {
      "caseInsensitiveSplitLookup": true,
      "trimResult": true,
      "collapseWhitespace": true
    }
  }
}
  };

  var normalizer = createNormalizer(data);

  globalThis.betterVoices = {
    normalize: normalizer.normalize,
    splitWord: normalizer.splitWord,
    profiles: data.profiles,
    version: "1.1.0"
  };
})();
